CREATE TABLE IF NOT EXISTS sprinkling (
	id integer PRIMARY KEY,
	room_id varchar(20),
	token varchar(3),
	requester varchar(20),
	total_amount integer,
	target_count integer,
	created_time timestamp DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS sprinkling_user (
	sprinkling_id integer,
	user_id varchar(20),
	amount integer,
	CONSTRAINT sprinkling_user_pk PRIMARY KEY (sprinkling_id, user_id),
	CONSTRAINT sprinkling_user_fk foreign KEY (sprinkling_id) references sprinkling (id)
);


CREATE TABLE IF NOT EXISTS sprinkling_divided_money (
	id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	sprinkling_id integer,
	amount integer,
	CONSTRAINT sprinkling_divided_money foreign KEY (sprinkling_id) references sprinkling (id)
);